[tool.poetry]
name = "pykasm"
version = "1.0.0"
description = "Extensions for multithreaded Python applications."
authors = ["Alexander Reynolds <alex@theory.shop>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
mypy = "^0.812"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
